eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

##将请求转发到对应模块进行处理
server:
  port: 9002

file:
    path: C:/code/work/join-test-two/DouDing/api-file/src/main/resources/f/


